<a href="https://colab.research.google.com/github/FariaJ65/LOGISTIC-REGRESSION/blob/main/Advertisement_Sale_prediction_from_an_existing_customer_using_LOGISTIC_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive' ,force_remount=True)

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# Regression
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
# Preprocessing :
from sklearn.preprocessing import  StandardScaler, LabelEncoder, Normalizer 

In [ ]:
# Classification
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score, classification_report

In [ ]:
# Read datasets
dataset = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/dataset/Social_Network_Ads.csv")
dataset.head()
dataset.shape

(400, 3)

In [ ]:
X=dataset.iloc[:,:-1].values
X

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


In [ ]:
Y=dataset.iloc[:,-1].values
Y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 7)

In [ ]:
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
X_train

array([[ 0.59531408,  1.95866234],
       [-0.71170063, -0.23323283],
       [ 0.22188131, -0.37556368],
       [-0.15155147,  1.36087275],
       [-0.89841702, -0.9448871 ],
       [ 1.15546324, -0.74562391],
       [-1.83199895, -0.0624358 ],
       [-0.80505882,  0.27915825],
       [ 0.3152395 ,  0.05142888],
       [-0.15155147,  2.1009932 ],
       [ 1.90232879, -0.91642093],
       [-1.27184979, -0.43249603],
       [-0.71170063, -0.60329305],
       [-1.0851334 , -0.77409008],
       [-1.36520798, -0.11936814],
       [ 0.96874685,  2.01559468],
       [-0.80505882,  0.1368274 ],
       [ 1.24882144,  1.81633149],
       [-0.33826785, -0.77409008],
       [ 1.90232879,  0.87694784],
       [-0.43162605,  1.2185419 ],
       [ 1.52889602,  0.96234636],
       [-1.73864076, -1.40034584],
       [ 0.3152395 , -0.51789454],
       [ 0.40859769,  0.07989505],
       [ 0.87538866, -1.28648116],
       [ 1.7156124 ,  1.78786532],
       [-0.15155147, -0.4609622 ],
       [-0.24490966,

In [ ]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
pred = model.predict(X_test)
print(classification_report(Y_test, pred))

              precision    recall  f1-score   support

           0       0.91      0.88      0.90        68
           1       0.76      0.81      0.79        32

    accuracy                           0.86       100
   macro avg       0.84      0.85      0.84       100
weighted avg       0.86      0.86      0.86       100



In [ ]:
age=int(input("Enter new custopmers age:"))
salary=int(input("Enter new custopmers salary:"))
newcust=[[age,salary]]
result = model.predict(sc.transform(newcust))
print(result)
if result == 1:
  print("Customer will buy")
else:
  print("Customer will not buy")



Enter new custopmers age:25
Enter new custopmers salary:18200
[1]
Customer will buy
